-- ===================================================================
-- Magnitude Analysis: Compare the measure values by categories.
-- ===================================================================

-- Find total customers by countries
SELECT TOP 5 * FROM gold.dim_customers;

SELECT COUNT(customer_key) total_customers, country
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC; -- LOW CARDINALITY dimension 'country'

-- Find total customers by gender
SELECT COUNT(customer_key) total_customers, gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC; -- LOW CARDINALITY dimension 'gender'

-- Find total products by category
SELECT TOP 5 * FROM gold.dim_products;

SELECT COUNT(product_name) AS total_products
FROM gold.dim_products;

SELECT COUNT(product_name) AS total_products, category  -- OR COUNT(product_key)
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC; -- LOW CARDINALITY dimension 'category'

-- What is the average cost in each product category ???
SELECT AVG(cost) AS avg_cost, category
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC; -- LOW CARDINALITY dimension 'category'

SELECT TOP 5 * FROM gold.fact_sales;

-- What is the total revenue generated for each category ???
SELECT dp.category, SUM(fs.sales_amount) AS revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY revenue DESC; -- LOW CARDINALITY dimension 'category'

-- For a fuller breakdown:
SELECT dp.category, 
	   COUNT(DISTINCT fs.order_number) AS total_orders,
	   SUM(fs.quantity) total_qty,
	   AVG(fs.price) avg_price,
	   SUM(fs.sales_amount) revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY revenue DESC;

-- What is the total revenue generated by each customer ???
SELECT TOP 5 * FROM gold.dim_customers;

SELECT dc.customer_key,
       CONCAT(dc.first_name, ' ', dc.last_name) customer_name,
       SUM(fs.sales_amount) revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON dc.customer_key = fs.customer_key
GROUP BY dc.customer_key, CONCAT(dc.first_name, ' ', dc.last_name)
ORDER BY revenue DESC; -- HIGH CARDINALITY dimension 'customer_key'
--- OR ---
SELECT dc.customer_key, dc.first_name, dc.last_name,
       SUM(fs.sales_amount) revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON dc.customer_key = fs.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY revenue DESC;

-- What is the distribution of sold items across countries ???
SELECT dc.country, SUM(fs.quantity) sold_items
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON dc.customer_key = fs.customer_key
GROUP BY dc.country
ORDER BY sold_items DESC;  -- LOW CARDINALITY dimension 'country'
